[package]
name = "hamilton"
version = "0.1.0"
authors = ["David Weis <dweis7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.3"
tokio = { version = "0.2", features = ["macros", "time"] }
prost = "0.6"
clap = "3.0.0-beta.1"
tokio-serial = { version = "4.3", default-features = false }
bytes = "0.5"
async-trait = "0.1"
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
postcard-cobs = "0.1.5-pre"
tokio-util = { version = "0.3", features = ["codec"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "3.0"
lss_driver = "0.4"

[build-dependencies]
tonic-build = { version = "0.3", features = ["prost"] }

[dev-dependencies]
assert_approx_eq = "1.1"
